eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka
  instance:
    hostname: eureka-discovery-service

management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: never

server:
  error:
    include-binding-errors: never
    include-message: never
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: true
  port: 8080

spring:
  main:
    banner-mode: off
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: google-route
          uri: https://google.com
          predicates:
            - Path=/google/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Routed-By,Gateway
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8081/realms/nucleus/protocol/openid-connect/token/introspect
          client-id: nucleus
          client-secret: YqRiH7JPmffolO28xMLAp9q3dLFzVPqy